baseURL = "http://github.com/brandonleekramer/"
languageCode = "en-us"
#title = "Impacts & Echoes"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Brandon Kramer"
    description = "This website outlines the lasting effect of the White House Conference on Food, Nutrition and Health"
    githubUsername = "brandonleekramer"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Impacts & Echoes"
    weight = 1

[[menu.main]]
    url = "/whc-text-network/"
    name = "WHC Text Network"
    weight = 2

[[menu.main]]
    url = "/interactive-timelines/"
    name = "Timelines"
    weight = 3

[[menu.main]]
    url = "/text-analysis-1919-1989/"
    name = "Topic Trends (1919-1989)"
    weight = 4
    
[[menu.main]]
    url = "/text-analysis-1990-2018/"
    name = "Topic Trends (1990-2018)"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://biocomplexity.virginia.edu/social-decision-analytics/"
    name = "university"
    weight = 1

[[menu.icon]]
    url = "mailto:brandonleekramer@gmail.com"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/brandonleekramer/"
    name = "github"
    weight = 3






